New docs
aurelia/aurelia pull request #1134
Opened 2021-03-12 14:51 UTC by HamedFathi

### Getting Started

* Bindable Setter

### Advanced Scenarios

* CSS-in-JS with Emotion
* TailwindCSS Integration
* Write Custom Plugin

2021-03-12 15:41 UTC, AureliaEffect commented
The benchmarking comparison can be found here: https://au2-bench-viewer.azurewebsites.net/compare?branch=master&commit=0a2d77e206923bcabe43486a3d847f51569b9663&branch=new-docs&commit=827dc3ad5b2b045585a021beb99e39861321991c

2021-03-12 20:00 UTC, AureliaEffect commented
The benchmarking comparison can be found here: https://au2-bench-viewer.azurewebsites.net/compare?branch=master&commit=0a2d77e206923bcabe43486a3d847f51569b9663&branch=new-docs&commit=522590a688080450db1095d5fff688dd3b617e86

2021-03-13 10:09 UTC, AureliaEffect commented
The benchmarking comparison can be found here: https://au2-bench-viewer.azurewebsites.net/compare?branch=master&commit=0a2d77e206923bcabe43486a3d847f51569b9663&branch=new-docs&commit=b79ba4874b6c40bc82e6e79ef8ffadd004c6750e

2021-03-13 11:47 UTC, Vheissu requested changes

2021-03-13 11:47 UTC, Vheissu commented on docs/user-docs/advanced-scenarios/css-in-js-with-emotion.md
> +**Why shadow-root matter?**
This should read, "Why does shadow-root matter?"

2021-03-13 11:47 UTC, Vheissu commented on docs/user-docs/advanced-scenarios/css-in-js-with-emotion.md
> +This method helps us to find out our HTMLElement is inside a shadow-root or not.
Should read, "This method helps us to find out if our HTMLElement is inside of a shadow-root or not.

2021-03-13 15:34 UTC, AureliaEffect commented
The benchmarking comparison can be found here: https://au2-bench-viewer.azurewebsites.net/compare?branch=master&commit=0a2d77e206923bcabe43486a3d847f51569b9663&branch=new-docs&commit=84e2ce81b397b9407bf89843a0d7ac1b9c922077

2021-03-18 22:14 UTC, AureliaEffect commented
The benchmarking comparison can be found here: https://au2-bench-viewer.azurewebsites.net/compare?branch=master&commit=ec47fe936caf13cc385d4039ef7f09b2bbce1fd4&branch=new-docs&commit=69f84598bfc72940ef6b6503831b49b3da6166fd

2021-03-19 08:30 UTC, Vheissu approved these changes
This all looks great. Let's get it in.

2021-03-19 09:19 UTC, HamedFathi commented
@fkleuver 
Seems ready to merge. If you have any comments let me know.
Thanks.

2021-03-19 13:40 UTC, merged