refactor(enhance): change working mechanism of enhance to the same with v1
aurelia/aurelia pull request #1247
Opened 2021-07-18 01:16 UTC by bigopon

# Pull Request

## 📖 Description

At the moment, `Aurelia.enhance` works similarly to `Aurelia.app`: it would become an application root of itself. While this gives some interesting perspective to look at enhance, it makes the usage of enhance more difficult than the method name suggests. Change the way `Aurelia.enhance` work to the same with `enhance` in v1.

CHANGES:
- remove: root requirement in `Controller.forCustomElement`, `Controller.forSyntheticView`, `Controller.forCustomAttribute`: it shouldn't require irrelevant information to the construction of a controller. The existing internal way to halt/resume hydration is moved to hydration instruction.
- remove: root property in `IController`/`Controller`. This should give some more perf boost.

## ⏭ Next Steps

- doc: add examples how to create a view factory
- doc: add examples how to apply a custom attribute dynamically to an element

2021-07-18 13:08 UTC, bigopon commented
@jwx After this PR, `Controller.forCustomElement` will only need own container, vm instance and host for the usage in the router.

2021-07-18 16:27 UTC, Sayan751 requested changes
Great work! Liked the re-usage of the root container.

Left couple of comments regarding some refactoring, and missing tests. Also tried to answer some questions.

2021-07-18 16:27 UTC, Sayan751 commented on packages/runtime-html/src/aurelia.ts
> +  resources?: unknown[];
I think this to be bit superfluous, as the resources can be registered to the `container`. Also as the docs is silent about this I think this should be removed. Instead we can point out in the doc that any additional resources those are not yet registered to the root container, can be registered now.

2021-07-18 16:27 UTC, Sayan751 commented on packages/runtime-html/src/aurelia.ts
> +  container?: IContainer;
IMO when this is provided it should be treated as "the" container for the enhance instead of treating it as the "parent" container. If there are resources registered to this, the it will save us going one step up while resolving dependencies. When done so, then the container assignment in enhance can be changed as follows:

```diff
-  const ctn = config.container ?? this.container;
-  const childCtn = ctn.createChild();
+  const ctn = config.container ?? this.container.createChild();
```

I think the resulting API might be more transparent that way.

```typescript
const container = injectedOrRootContainer.createChild().register(...additionResources);
const view = await au.enhance({container, ...})
```

2021-07-18 16:27 UTC, Sayan751 commented on packages/__tests__/3-runtime-html/enhance.spec.ts
> +import { Constructable, DI, IContainer, ILogEvent, InstanceProvider, ISink, LogLevel, Registration } from '@aurelia/kernel';
IMO following tests are missing:

- re-activate deactivated enhanced node (enhance -> deactivate -> activate)
- attempt to re-enhance a node
  - enhance -> enhance
  - enhance -> deactivate -> enhance
  - enhance -> deactivate -> activate -> enhance

2021-07-19 03:07 UTC, bigopon commented on packages/runtime-html/src/aurelia.ts
> +  container?: IContainer;
At the moment, we are doing the same thing in `aurelia.app`, we do not open a way to create the container for the root element. I was trying to keep it consistent that way, since this is refactored from the existing enhance. Maybe we should give up the control here.

2021-07-19 03:08 UTC, bigopon commented on packages/__tests__/3-runtime-html/enhance.spec.ts
> +    assert.strictEqual(component.myElController === parentController, true);
I had a typo in the template and it printed 4~5 pages of log in the console. Used it to check, forgot to turn it back.

2021-07-19 09:19 UTC, bigopon commented on packages/runtime-html/src/aurelia.ts
> +      deactivate: () => view.deactivate(view, parentController!, LifecycleFlags.fromUnbind)
the APIs around activation and deactivation aren't that great where we would potentially supply 2 redundant parameters. But we probably can embrace it for now and keep things plain here.

2021-07-19 09:27 UTC, bigopon commented on packages/runtime-html/src/template-compiler.ts
> +
String concatenation seems to look much clean, what alternative do you propose?

2021-07-19 10:04 UTC, bigopon commented on packages/runtime-html/src/aurelia.ts
> +  // Aurelia.root of a controller hierarchy should behave similarly
we can enhance our `IHydrationContext` so that it has another property pointing at the root of **a hydration process**. At the moment, the `IAppRoot` isn't that useful, and it's not providing any useful information either.

2021-07-19 10:38 UTC, bigopon commented on docs/user-docs/getting-to-know-aurelia/app-configuration-and-startup.md
> +await au.enhance({ host, component: MyComponent });
>  the existing registrations will work.

I think this is the default expectation, we probably shouldn't mention it.

2021-07-19 10:53 UTC, bigopon commented
Thanks @Sayan751, I've addressed your comments, including the doc. I'll go with alpha 13 now, and address future comments if any.

2021-07-19 10:53 UTC, merged